apiVersion: v1
kind: Service
metadata:
  namespace: voting-app
  labels:
    app: result
  name: result
spec:
  type: NodePort
  ports:
  - name: "result-service"
    port: 80
    targetPort: 8080
    nodePort: 31001
  selector:
    app: result
