apiVersion: v1
kind: Service
metadata:
  namespace: voting-app
  labels:
    app: vote
  name: vote
spec:
  type: ClusterIP 
  ports:
  - name: "vote-service"
    port: 80        
    targetPort: 8080 
  selector:
    app: vote
